### ISSUE TITLE
Implement cleaner Rendering process

### ISSUE THREAD

**Issue by Kaezon** [Kaezon/python-space2d#2]
Currently, `dirty_rects` is updated in any individual processor which moves a Renderable around. I think this will cause the rendering process to become exceptionally difficult to debug and maintain. The goal should be to have a more centralized handling of Renderable invalidation and handle all blits in `RenderProcessor`.

**Questions:**
- [x] How are off-screen rects handled?
- [x] How do I determine the original screen location of an invalidated renderable?

**Tasks:**

- [ ] Implement `Renderable.invalidate()`
- [ ] Update `worldToScreenCoords` with distinct feedback for off-screen coordinates
- [ ] Update `worldToScreenRect` with distinct feedback for off-screen rects
- [ ] Update `RenderProcessor` so it handles the the updated renderable data correctly.

**Comment by Kaezon** [comment]
Answers:
1.) worldToScreen functions should return `None` for more elegant handling
2.) store a screen space Rect in the component
